server:
  servlet:
    context-path: "/api"

spring:
  data:
    mongodb:
      host: ${VBR_DB_HOST:}
      port: ${VBR_DB_PORT:}
      database: ${VBR_DB:}
      username: ${VBR_DB_USER:}
      password: ${VBR_DB_PASSWORD:}
  cache:
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider

vbr:
  jwt:
    key: ${VBR_JWT_KEY:}

logging:
  config: classpath:logback-spring.xml