server:
  servlet:
    context-path: "/api/v3.2"

spring:
  data:
    mongodb:
      host: ${VBR_DB_HOST:}
      port: ${VBR_DB_PORT:}
      database: ${VBR_DB:}
      username: ${VBR_DB_USER:}
      password: ${VBR_DB_PASSWORD:}

vbr:
  jwt:
    key: ${VBR_JWT_KEY:}
  web:
    domain: ${VBR_DOMAIN:}
    color: ${VBR_COLOR:}
  android:
    app:
      packageName: ${VBR_ANDROID_PACKAGE:}
      billing:
        credential: ${VBR_ANDROID_BILLING_CREDENTIALS:}
        sku-purchase: ${VBR_ANDROID_BILLING_PURCHASE_SKU:}
        sku-subscription: ${VBR_ANDROID_BILLING_SUBSCRIPTION_SKU:}
  email:
    user: ${VBR_EMAIL_USER:}
    password: ${VBR_EMAIL_PASSWORD:}

logging:
  config: classpath:logback-spring.xml