spring.profiles: integration
spring.data.mongodb.uri: mongodb://vbr_integ_user:vbr@localhost:27017/vbr_integ

vbr:
  auth:
    facebookAppAccessToken: 2086514551632301|EShvFJ7FGAKChTSlqOXolTmcdVM
    googleWebClientId: 802590775795-kdff0cnflla62jr2dj0pleqbiv05q97l.apps.googleusercontent.com
    signUpKey: 161adaea-90a1-46b7-be28-b27c0837aea8

---
spring.profiles: production
spring.data.mongodb.uri: mongodb://vbr_user:vbr@localhost:27017/vbr

vbr:
  auth:
    facebookAppAccessToken: 2086514551632301|EShvFJ7FGAKChTSlqOXolTmcdVM
    googleWebClientId: 802590775795-kdff0cnflla62jr2dj0pleqbiv05q97l.apps.googleusercontent.com
    signUpKey: d14e2e45-0475-43ac-b6e4-56aae0e383fc

logging:
  config: classpath:logback-spring.xml
